# -*- coding: utf-8 -*-
"""task4_solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-H9LQ9U_3qpaahDND8P9AHwleowMa9G
"""

import pandas as pd
import requests

r = requests.get('https://api.covid19api.com/total/country/singapore')
data = r.text
df = pd.read_json(data, orient='records')
print(df[["Confirmed","Deaths","Active", "Date"]])
df["Date"]= pd.to_datetime(df.Date)

import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(
        rows=3, cols=1,
        subplot_titles=("Confirmed Cases of All Time - SG", 
                        "Deaths of All Time - SG", 
                        "Active Cases of All Time - SG")
        )

fig.add_trace(go.Scatter(x=df["Date"].to_numpy(),y=df["Confirmed"].to_numpy(),
                         name='Confirmed Cases',
                         mode="lines",
                         line=dict(color='orange')),
                         row=1, col=1
                         )
fig.add_trace(go.Scatter(x=df["Date"].to_numpy(),y=df["Deaths"].to_numpy(),
                         name='Deaths',
                         mode="lines",
                         line=dict(color='red')),
                         row=2, col=1
                         )
fig.add_trace(go.Scatter(x=df["Date"].to_numpy(),y=df["Active"].to_numpy(),
                         name='Active',
                         mode="lines",
                         line=dict(color='blue')),
                         row=3, col=1
                         )

fig.update_layout(height=1000)

import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2)

fig = px.line(df, x="Date", y="Confirmed", 
              title="Confirmed Cases of All Time - Singapore")

fig['data'][0]['line']['color']="orange"
fig.show()

fig = px.line(df, x="Date", y="Deaths", title="Confirmed Deaths of All Time - Singapore")
fig['data'][0]['line']['color']="red"
fig.show()

fig = px.line(df, x="Date", y="Active", title="Active Cases of All Time - Singapore")
fig['data'][0]['line']['color']="blue"
fig.show()