# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-H9LQ9U_3qpaahDND8P9AHwleowMa9G
"""

import pandas as pd
import requests
import plotly.graph_objects as go
import plotly.express as px

r = requests.get('https://api.covid19api.com/total/country/singapore')
data = r.text
df = pd.read_json(data, orient='records')
print(df[["Confirmed","Deaths","Active", "Date"]])
df["Date"]= pd.to_datetime(df.Date)


fig = px.line(df, x="Date", y="Confirmed", 
              title="Confirmed Cases of All Time - Singapore")

fig['data'][0]['line']['color']="orange"
fig.show()

fig = px.line(df, x="Date", y="Deaths", title="Confirmed Deaths of All Time - Singapore")
fig['data'][0]['line']['color']="red"
fig.show()

fig = px.line(df, x="Date", y="Active", title="Active Cases of All Time - Singapore")
fig['data'][0]['line']['color']="blue"
fig.show()



fig = go.Figure()
fig.add_trace(go.Scatter(x=df["Date"].to_numpy(),y=df["Confirmed"].to_numpy(),
                         name='Confirmed Cases',
                         mode="lines",
                         line=dict(color='orange')))
fig.add_trace(go.Scatter(x=df["Date"].to_numpy(),y=df["Deaths"].to_numpy(),
                         name='Deaths',
                         mode="lines",
                         line=dict(color='red')))
fig.add_trace(go.Scatter(x=df["Date"].to_numpy(),y=df["Active"].to_numpy(),
                         name='Active',
                         mode="lines",
                         line=dict(color='blue')))