version: '3.8'
services:
    postgres:
        image: postgres:12.10
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgrespw
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # create tables on container start up
          - ./SQL/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # populate tables after contianer start up
          # - ./SQL/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql